일부 수정

diff --git a/tools/release b/tools/release
--- a/tools/release
+++ b/tools/release
@@ -27,11 +27,9 @@ GEM_SPEC="jekyll-theme-chirpy.gemspec"
 
 NODE_CONFIG="package.json"
 
-JS_DIST="assets/js/dist"
-BACKUP_PATH="$(mktemp -d)"
-
 FILES=(
   "_sass/jekyll-theme-chirpy.scss"
+  "_javascript/copyright"
   "$GEM_SPEC"
   "$NODE_CONFIG"
 )
@@ -48,7 +46,7 @@ help() {
   echo
   echo "Usage:"
   echo
-  echo "   bash ./tools/release [options]"
+  echo "   bash ./tools/release.sh [options]"
   echo
   echo "Options:"
   echo "     -k, --skip-versioning    Skip the step of generating the version number."
@@ -71,24 +69,17 @@ _check_git() {
 }
 
 _check_src() {
-  for i in "${!FILES[@]}"; do
-    _src="${FILES[$i]}"
-    if [[ ! -f $_src && ! -d $_src ]]; then
-      echo -e "Error: Missing file \"$_src\"!\n"
-      exit 1
-    fi
-  done
-
+  if [[ ! -f $1 && ! -d $1 ]]; then
+    echo -e "Error: Missing file \"$1\"!\n"
+    exit 1
+  fi
 }
 
 _check_command() {
-  for i in "${!TOOLS[@]}"; do
-    cli="${TOOLS[$i]}"
-    if ! command -v "$cli" &>/dev/null; then
-      echo "Command '$cli' not found!"
-      exit 1
-    fi
-  done
+  if ! command -v "$1" &>/dev/null; then
+    echo "Command '$1' not found"
+    exit 1
+  fi
 }
 
 _check_node_packages() {
@@ -98,13 +89,20 @@ _check_node_packages() {
 }
 
 check() {
-  _check_command
   _check_git
-  _check_src
+
+  for i in "${!FILES[@]}"; do
+    _check_src "${FILES[$i]}"
+  done
+
+  for i in "${!TOOLS[@]}"; do
+    _check_command "${TOOLS[$i]}"
+  done
+
   _check_node_packages
 }
 
-_bump_files() {
+_bump_file() {
   for i in "${!FILES[@]}"; do
     if [[ ${FILES[$i]} == "$NODE_CONFIG" ]]; then
       continue
@@ -113,7 +111,7 @@ _bump_files() {
     sed -i "s/v[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+/v$1/" "${FILES[$i]}"
   done
 
-  npm run build
+  npx gulp
 }
 
 _bump_gemspec() {
@@ -129,7 +127,7 @@ _bump_gemspec() {
 #
 # 2. Create a commit to save the changes.
 bump() {
-  _bump_files "$1"
+  _bump_file "$1"
   _bump_gemspec "$1"
 
   if [[ $opt_pre = false && -n $(git status . -s) ]]; then
@@ -153,10 +151,7 @@ build_gem() {
   echo -e "Build the gem package for v$_version\n"
   cleanup_config
   rm -f ./*.gem
-  git add "$JS_DIST" -f # add JS dist to gem
   gem build "$GEM_SPEC"
-  cp "$JS_DIST"/* "$BACKUP_PATH"
-  git restore --staged "$JS_DIST" # resume the git status
   resume_config
 }
 
@@ -164,14 +159,15 @@ build_gem() {
 release() {
   _version="$1" # X.Y.Z
 
-  git checkout "$PROD_BRANCH"
-  git merge --no-ff --no-edit "$working_branch"
-
   # Create a new tag on working branch
   echo -e "Create tag v$_version\n"
   git tag "v$_version"
 
-  # Merge from patch branch to the staging branch
+  git checkout "$PROD_BRANCH"
+  git merge --no-ff --no-edit "$working_branch"
+
+  # merge from patch branch to the staging branch
+  # NOTE: This may break due to merge conflicts, so it may need to be resolved manually.
   if [[ $working_branch == hotfix/* ]]; then
     git checkout "$STAGING_BRANCH"
     git merge --no-ff --no-edit "$working_branch"
@@ -193,8 +189,6 @@ main() {
 
   # Change heading of Patch version to level 2 (a bug from `standard-version`)
   sed -i "s/^### \[/## \[/g" CHANGELOG.md
-  # Replace multiple empty lines with a single empty line
-  sed -i "/^$/N;/^\n$/D" CHANGELOG.md
 
   _version="$(grep '"version":' "$NODE_CONFIG" | sed 's/.*: "//;s/".*//')"
 
@@ -209,9 +203,6 @@ main() {
   else
     release "$_version"
   fi
-
-  # restore the dist files for future development
-  mkdir -p "$JS_DIST" && cp "$BACKUP_PATH"/* "$JS_DIST"
 }
 
 while (($#)); do
